### ISSUE TITLE
Access Token on .env

### ISSUE THREAD

**Issue by jhourlad** [danrichards/shopify#17]
Been looking around Shopify admin but it doesn't look like the token to be filled in to the SHOPIFY_TOKEN key is anywhere on the admin.  Any notes on this?

**Comment by danrichards** [comment]
![Screenshot 2023-03-25 at 6 39 10 PM](https://user-images.githubusercontent.com/470255/227745643-823146dc-02d3-4abb-863a-af3092508ef7.png)
