### ISSUE TITLE
Not able to install version 2

### ISSUE THREAD

**Issue by javiernunez** [danrichards/shopify#18]
When I try to install the package (as in  the DOC) 

```bash
composer require dan/shopify-api v2.*
```
I get:

```bash                                                                   
  [InvalidArgumentException]                                         
  Could not find package dan/shopify-api in a version matching v2.*                                                                  
```

**Comment by squatto** [comment]
@javiernunez the command you need to run is actually:

```shell
composer require dan/shopify v2.*
```

The package name is different (`dan/shopify`, not `dan/shopify-api`). The readme in this repo needs to be corrected to reflect the change.

EDIT: I submitted a PR #20 to change the readme 👍🏻
